[package]
name = "web_guard"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
description.workspace = true
license.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
rslock.workspace = true